apiVersion: v1
kind: Service
metadata:
  name: {{ include "litecoind.fullname" . }}
  labels:
    {{- include "litecoind.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports: []
  selector:
    {{- include "litecoind.selectorLabels" . | nindent 4 }}
